# Generated by Django 5.2.8 on 2025-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
