# Generated by Django 5.2.8 on 2025-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_produit_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='produits'),
        ),
    ]
