# Generated by Django 5.2.8 on 2025-11-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_produit_slug_alter_produit_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('prep', 'Préparée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('retournee', 'Retournée')], default='prep', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
            ],
        ),
    ]
