# Generated by Django 5.2.8 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livraison',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_effective',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='livraison',
            name='transport',
            field=models.CharField(blank=True, choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('a_pied', 'À pied'), ('trottinette', 'Trottinette')], max_length=30, null=True),
        ),
    ]
