# Generated by Django 5.1.7 on 2025-11-15 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_livraison_adresse_livraison_livraison_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='approved',
            field=models.BooleanField(default=False, help_text="Validé par l'admin pour vendre"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Détails bancaires pour versement', max_length=255),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de commission (%) prélevé par la plateforme', max_digits=5),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # NOTE: user ajouté temporairement nullable pour permettre migration sur DB existante
        migrations.AddField(
            model_name='fournisseur',
            name='user',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='created_at',
            # Fournir un default valide pour backfill lors de la migration
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandes.produit'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande'),
        ),
        # correction de la faute de frappe -> AlterField
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='commandes.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]