# Generated by Django 5.2.8 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_alter_fournisseur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='livraison',
            name='methode',
            field=models.CharField(choices=[('camion', 'Camion'), ('moto', 'Moto'), ('velo', 'Vélo')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
