# Generated by Django 5.2.8 on 2025-11-18 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_livraison_adresse_livraison_methode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['-date_prevue'], 'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='methode',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
